services:
  # Service Database Neo4j
  neo4j:
    image: neo4j:latest
    container_name: graphweaver_db
    ports:
      - "7474:7474"  # Dashboard HTTP
      - "7687:7687"  # Bolt Port
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD} # Mengambil password dari .env
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
    volumes:
      - ./neo4j_data:/data
      - ./neo4j_logs:/logs
    restart: unless-stopped

  # Service Aplikasi Python
  app:
    build: .
    container_name: graphweaver_app
    ports:
      - "8000:8000"
    env_file:
      - .env # Menggunakan variabel lingkungan dari file .env
    depends_on:
      - neo4j # Pastikan DB jalan duluan
    restart: unless-stopped